telegram.bots:
  botToken: ${BOT_ORCHARD_TOKEN}
  botUserName: ${BOT_ORCHARD_USER_NAME}
  users:
    admin: ${BOT_ORCHARD_ADMIN_USER}
    allowed: '${BOT_ORCHARD_ALLOWED_USERS}, ${telegram.bots.users.admin}' 